language: java
before_install:
  - chmod +x gradlew
script:
- ./gradlew build
env:
  - SPRING_DATASOURCE_URL=jdbc:postgresql://ec2-35-171-57-132.compute-1.amazonaws.com:5432/dbcfnuk3cpsvhr?password=e1ef6412b6bad33483f1298170976962c3f3256ddfec7b2f9762fce73278a709&sslmode=require&user=rferwkxdmafrho